language: php
php:
  - '7.1'
install:
  - composer install
before_script:
  - sudo apt-get update
  - sudo apt-get install curl software-properties-common
  -  curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
  - sudo apt-get install -y nodejs